#!/bin/bash

if [ "$1" == "" ]; then
    echo "Provie comment for commit."
    return 1
fi
    
git add reboot_framework.h reboot_framework.c reboot_tests.c qikgit TODO
git commit -m "$1"
git push
saints.fanatic@yahoo.com

return 0
