#!/bin/bash

if [ "$1" == "" ]; then
    echo "Provide comment for commit."
    return 1
fi
    
git add reboot_framework.h reboot_framework.c reboot_tests.c shell_interface/* myshell.c TODO ENDTESTS
git commit -m "$1"
git push

return 0
